/* The following code was generated by JFlex 1.4.1 on 01/11/16 11:51 */

/*
 * 04/27/2010
 *
 * TouistlTokenMaker.java - Scanner for Touistl.
 * 
 * This library is distributed under a modified BSD license.  See the included
 * RSyntaxTextArea.License.txt file for details.
 */
package gui.editionView.editor;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 01/11/16 11:51 from the specification file
 * <tt>Touistl.jflex</tt>
 */
public class TouistlTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\1\0\1\3\1\0\22\0\1\3\1\42\2\0"+
    "\1\7\3\0\1\41\1\41\1\41\1\41\1\41\1\41\1\6\1\41"+
    "\12\1\1\41\1\10\1\44\1\43\1\45\1\7\1\0\1\2\1\40"+
    "\21\2\1\37\6\2\1\41\1\0\1\41\1\0\1\4\1\0\1\12"+
    "\1\24\1\34\1\11\1\17\1\15\1\25\1\16\1\14\2\2\1\21"+
    "\1\30\1\20\1\26\1\31\1\35\1\27\1\22\1\13\1\33\1\2"+
    "\1\23\1\36\1\32\1\2\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\3\1"+
    "\20\3\1\6\1\1\2\6\3\0\1\7\1\10\6\3"+
    "\1\11\1\12\10\3\1\12\3\3\1\6\1\13\14\3"+
    "\1\14\4\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\46\0\344"+
    "\0\u010a\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214"+
    "\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2\0\u02f8\0\u031e\0\u0344"+
    "\0\u036a\0\u0390\0\46\0\u03b6\0\u03dc\0\u0402\0\276\0\u0428"+
    "\0\u010a\0\u044e\0\u0474\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532"+
    "\0\u0558\0\162\0\u057e\0\u05a4\0\u05ca\0\u05f0\0\u0616\0\u057e"+
    "\0\u063c\0\u0662\0\u0688\0\162\0\u06ae\0\u06d4\0\u06fa\0\u0720"+
    "\0\u0428\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de\0\u0804\0\u082a"+
    "\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8\0\162\0\u090e\0\u0934"+
    "\0\u095a\0\u0980";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\4\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\4\1\26\1\4"+
    "\1\27\3\4\1\30\2\4\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\33\47\0\1\3\1\4\1\0\1\37"+
    "\1\0\1\40\2\0\30\4\6\0\2\4\1\0\1\4"+
    "\4\0\30\4\10\0\1\5\43\0\1\37\1\4\1\0"+
    "\1\37\4\0\30\4\13\0\1\33\40\0\1\41\1\42"+
    "\1\0\1\41\4\0\30\42\15\0\1\43\36\0\2\4"+
    "\1\0\1\4\4\0\1\4\1\44\1\4\1\45\24\4"+
    "\6\0\2\4\1\0\1\4\4\0\2\4\1\46\4\4"+
    "\1\47\20\4\6\0\2\4\1\0\1\4\4\0\5\4"+
    "\1\50\10\4\1\51\11\4\6\0\2\4\1\0\1\4"+
    "\4\0\4\4\1\52\2\4\1\53\20\4\6\0\2\4"+
    "\1\0\1\4\4\0\1\4\1\54\26\4\6\0\2\4"+
    "\1\0\1\4\4\0\7\4\1\47\1\55\6\4\1\56"+
    "\5\4\1\57\2\4\6\0\2\4\1\0\1\4\4\0"+
    "\15\4\1\60\12\4\6\0\2\4\1\0\1\4\4\0"+
    "\6\4\1\60\21\4\6\0\2\4\1\0\1\4\4\0"+
    "\22\4\1\61\1\4\1\62\3\4\6\0\2\4\1\0"+
    "\1\4\4\0\5\4\1\50\22\4\6\0\2\4\1\0"+
    "\1\4\4\0\3\4\1\63\24\4\6\0\2\4\1\0"+
    "\1\4\4\0\16\4\1\64\11\4\6\0\2\4\1\0"+
    "\1\4\4\0\15\4\1\47\12\4\6\0\2\4\1\0"+
    "\1\4\4\0\1\4\1\65\26\4\6\0\2\4\1\0"+
    "\1\4\4\0\15\4\1\66\12\4\6\0\2\4\1\0"+
    "\1\4\4\0\15\4\1\67\12\4\50\0\1\33\45\0"+
    "\1\33\1\0\1\33\43\0\1\70\3\0\1\71\45\0"+
    "\2\42\1\0\1\42\4\0\30\42\5\0\5\43\1\0"+
    "\40\43\1\0\2\4\1\0\1\4\4\0\2\4\1\72"+
    "\25\4\6\0\2\4\1\0\1\4\4\0\4\4\1\73"+
    "\23\4\6\0\2\4\1\0\1\4\4\0\10\4\1\74"+
    "\6\4\1\75\10\4\6\0\2\4\1\0\1\4\4\0"+
    "\1\64\27\4\6\0\2\4\1\0\1\4\4\0\6\4"+
    "\1\76\21\4\6\0\2\4\1\0\1\4\4\0\22\4"+
    "\1\77\5\4\6\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\64\25\4\6\0\2\4\1\0\1\4\4\0\10\4"+
    "\1\100\17\4\6\0\2\4\1\0\1\4\4\0\11\4"+
    "\1\101\16\4\6\0\2\4\1\0\1\4\4\0\20\4"+
    "\1\102\7\4\6\0\2\4\1\0\1\4\4\0\1\4"+
    "\1\103\26\4\6\0\2\4\1\0\1\4\4\0\13\4"+
    "\1\104\14\4\6\0\2\4\1\0\1\4\4\0\16\4"+
    "\1\60\11\4\6\0\2\4\1\0\1\4\4\0\14\4"+
    "\1\105\13\4\6\0\2\4\1\0\1\4\4\0\16\4"+
    "\1\47\11\4\6\0\2\4\1\0\1\4\4\0\20\4"+
    "\1\106\7\4\6\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\106\25\4\52\0\1\33\1\0\2\4\1\0\1\4"+
    "\4\0\1\4\1\52\26\4\6\0\2\4\1\0\1\4"+
    "\4\0\4\4\1\64\23\4\6\0\2\4\1\0\1\4"+
    "\4\0\6\4\1\107\21\4\6\0\2\4\1\0\1\4"+
    "\4\0\15\4\1\110\12\4\6\0\2\4\1\0\1\4"+
    "\4\0\7\4\1\52\20\4\6\0\2\4\1\0\1\4"+
    "\4\0\6\4\1\106\21\4\6\0\2\4\1\0\1\4"+
    "\4\0\11\4\1\77\16\4\6\0\2\4\1\0\1\4"+
    "\4\0\6\4\1\52\21\4\6\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\111\25\4\6\0\2\4\1\0\1\4"+
    "\4\0\23\4\1\60\4\4\6\0\2\4\1\0\1\4"+
    "\4\0\11\4\1\22\16\4\6\0\2\4\1\0\1\4"+
    "\4\0\1\4\1\112\13\4\1\26\12\4\6\0\2\4"+
    "\1\0\1\4\4\0\1\4\1\110\26\4\6\0\2\4"+
    "\1\0\1\4\4\0\11\4\1\60\16\4\6\0\2\4"+
    "\1\0\1\4\4\0\21\4\1\64\6\4\6\0\2\4"+
    "\1\0\1\4\4\0\7\4\1\47\20\4\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2470];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\1\11\23\1\1\11\3\1\3\0"+
    "\51\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[74];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public TouistlTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	@Override
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * {@inheritDoc}
	 */
	public String[] getLineCommentStartAndEnd(int languageIndex) {
		return new String[] { "//", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new TokenImpl();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() { // Patched version to keep!
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) { // Patched version to keep!
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TouistlTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public TouistlTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { addToken(Token.RESERVED_WORD);
          }
        case 13: break;
        case 3: 
          { addToken(Token.IDENTIFIER);
          }
        case 14: break;
        case 11: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 15: break;
        case 10: 
          { addToken(Token.FUNCTION);
          }
        case 16: break;
        case 4: 
          { addToken(Token.WHITESPACE);
          }
        case 17: break;
        case 7: 
          { addToken(Token.VARIABLE);
          }
        case 18: break;
        case 1: 
          { addToken(Token.ERROR_IDENTIFIER);
          }
        case 19: break;
        case 6: 
          { addToken(Token.OPERATOR);
          }
        case 20: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 21: break;
        case 12: 
          { addToken(Token.LITERAL_BOOLEAN);
          }
        case 22: break;
        case 8: 
          { addToken(Token.COMMENT_MARKUP);
          }
        case 23: break;
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 24: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 75: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
