/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editionView.editor;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import org.fife.ui.rsyntaxtextarea.*;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.fife.ui.rtextarea.RTextScrollPane;
/**
 *
 * @author alexis
 */
public class Editor extends RSyntaxTextArea  {
    
    private ArrayList<Integer> snipetsBegin;
    private ArrayList<Integer> snipetsEnd;
    
    class SnippetListener implements DocumentListener {
        
        
        
        @Override
        public void insertUpdate(DocumentEvent e) {
            int debInsert = e.getOffset();
            int len = e.getLength();
            
            for(int i = 0; i < snipetsBegin.size(); i++) {
                int snipetBegin = snipetsBegin.get(i);
                int snipetEnd = snipetsEnd.get(i);
                if(snipetBegin >= debInsert){
                    snipetsBegin.set(i, snipetBegin + len);
                    snipetsEnd.set(i, snipetEnd + len);
                }
                else if(snipetEnd >= debInsert) {
                    snipetsBegin.remove(i);
                    snipetsEnd.remove(i--);
                }
            }
        
        }

        
        
        
        @Override
        public void removeUpdate(DocumentEvent e) {
            int debRemove = e.getOffset();
            int len = e.getLength();
            for(int i = 0; i < snipetsBegin.size(); i++) {
                int snipetBegin = snipetsBegin.get(i);
                int snipetEnd = snipetsEnd.get(i);
                if(snipetBegin <= debRemove + len - 1 && snipetEnd >= debRemove) {
                    snipetsBegin.remove(i);
                    snipetsEnd.remove(i--);
                }
                else if(snipetBegin >= debRemove){
                    snipetsBegin.set(i, snipetBegin - len);
                    snipetsEnd.set(i, snipetEnd - len);
                }
            }
        }

        // WARNING This function is not intercepting characters update at all
        // but lines update. If we change a character to another, remove and insert are
        // called
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    }
    
    class SnippetRightAction extends AbstractAction {
        
        Editor E;
        
        public SnippetRightAction(Editor E) {
            super();
            this.E = E;
        }
        
        public void actionPerformed(ActionEvent e) {
            int curr = E.getSelectionEnd();
            for(int i = 0; i < snipetsBegin.size(); i++) {
                if(snipetsBegin.get(i) >= curr) {
                    E.setSelectionStart(snipetsBegin.get(i));
                    E.setSelectionEnd(snipetsEnd.get(i)+1);
                    return;
                }
            }
            if(snipetsBegin.size() != 0) {
                E.setSelectionStart(snipetsBegin.get(0));
                E.setSelectionEnd(snipetsEnd.get(0)+1);
            }
            
        }
    }
    
    class SnippetLeftAction extends AbstractAction {
        
        Editor E;
        
        public SnippetLeftAction(Editor E) {
            super();
            this.E = E;
        }
        
        public void actionPerformed(ActionEvent e) {
            int curr = E.getSelectionStart();
            for(int i = 0; i < snipetsBegin.size(); i++) {
                if(snipetsBegin.get(i) < curr) {
                    E.setSelectionStart(snipetsBegin.get(i));
                    E.setSelectionEnd(snipetsEnd.get(i)+1);
                    return;
                }
            }
            if(snipetsBegin.size() != 0) {
                E.setSelectionStart(snipetsBegin.get(snipetsBegin.size()-1));
                E.setSelectionEnd(snipetsEnd.get(snipetsEnd.size()-1)+1);
            }
            
        }
    }
    
    
    
    
    public Editor() throws IOException {
        
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
        
        // Class generated by jflex 
        atmf.putMapping("text/touistl", "gui.editionView.editor.TouistlTokenMaker");
        this.setSyntaxEditingStyle("text/touistl");
        
        // Defines the color, font police and style of the different tokens
        Theme t = Theme.load(new FileInputStream("ressources/touistTheme.xml"));
        t.apply(this);
        
        snipetsBegin = new ArrayList<Integer>();
        snipetsEnd = new ArrayList<Integer>();
        
        this.getDocument().addDocumentListener(new SnippetListener());
        String rightKeyStrokeAndKey = "control RIGHT";
        KeyStroke rightKeyStroke = KeyStroke.getKeyStroke(rightKeyStrokeAndKey);
        this.getInputMap().put(rightKeyStroke, rightKeyStrokeAndKey);
        this.getActionMap().put(rightKeyStrokeAndKey, new SnippetRightAction(this));
        String leftKeyStrokeAndKey = "control LEFT";
        KeyStroke leftKeyStroke = KeyStroke.getKeyStroke(leftKeyStrokeAndKey);
        this.getInputMap().put(leftKeyStroke, leftKeyStrokeAndKey);
        this.getActionMap().put(leftKeyStrokeAndKey, new SnippetRightAction(this));
        

    }
    
    public void addSnipet(int begin,int end) {
        snipetsBegin.add(begin);
        snipetsEnd.add(end);
        Collections.sort(snipetsBegin);
        Collections.sort(snipetsEnd);
    }
    
    
/* Example of Editor with line displaying in left column */
    
    public static void main(String args[]) {
        JFrame  frame = new JFrame ();
        Editor E = null;
        
        try {
             E = new Editor();
        }
        catch (IOException e) {
            System.err.println("Erreur lancement éditeur");
        }
        frame.add(E, BorderLayout.CENTER);
        frame.setSize(300,100);
        
        BufferedReader in = null ;
        try {
            in = new BufferedReader(new FileReader("compiler/test/foo.touistl"));
            StringBuilder sb = new StringBuilder();
            String line;
            while((line = in.readLine()) != null) {
                sb.append(line+"\n");
            }
            E.setText(sb.toString());
        }
        catch (IOException e) {
            System.err.println("Erreur ouverture du fichier test");
        }
        
        RTextScrollPane sp = new RTextScrollPane(E);
        sp.setLineNumbersEnabled(true);
        sp.setFoldIndicatorEnabled(true);
        
        frame.add(sp, BorderLayout.CENTER);
        frame.setVisible(true);
    }
    
}
