/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editionView.editor;

import java.awt.BorderLayout;
import org.fife.ui.rsyntaxtextarea.*;
import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import org.fife.ui.rtextarea.RTextScrollPane;
/**
 *
 * @author alexis
 */
public class Editor extends RSyntaxTextArea  {
    
    public Editor() throws IOException {
        AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
        
        // Class generated by jflex 
        atmf.putMapping("text/touistl", "gui.editionView.editor.TouistlTokenMaker");
        setSyntaxEditingStyle("text/touistl");
        
        // Defines the color, font police and style of the different tokens
        Theme t = Theme.load(new FileInputStream("ressources/touistTheme.xml"));
        t.apply(this);
        
    }
    
    
/* Example of Editor with line displaying in left column */
    
    public static void main(String args[]) {
        JFrame  frame = new JFrame ();
        Editor E = null;
        
        try {
             E = new Editor();
        }
        catch (IOException e) {
            System.err.println("Erreur lancement éditeur");
        }
        frame.add(E, BorderLayout.CENTER);
        frame.setSize(300,100);
        
        BufferedReader in = null ;
        try {
            in = new BufferedReader(new FileReader("compiler/test/foo.touistl"));
            StringBuilder sb = new StringBuilder();
            String line;
            while((line = in.readLine()) != null) {
                sb.append(line+"\n");
            }
            E.setText(sb.toString());
        }
        catch (IOException e) {
            System.err.println("Erreur ouverture du fichier test");
        }
        
        RTextScrollPane sp = new RTextScrollPane(E);
        sp.setLineNumbersEnabled(true);
        sp.setFoldIndicatorEnabled(true);
        
        frame.add(sp, BorderLayout.CENTER);
        frame.setVisible(true);
    }
    
}
