/*
 *
 * Project TouIST, 2015. Easily formalize and solve real-world sized problems
 * using propositional logic and linear theory of reals with a nice GUI.
 *
 * https://github.com/olzd/touist
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * Contributors:
 *     Alexis Comte, Abdelwahab Heba, Olivier Lezaud,
 *     Skander Ben Slimane, Maël Valais
 *
 */

package gui.editorView;

import gui.AbstractComponentPanel;
import gui.State;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Skander
 */
public class FormulaPanel extends AbstractComponentPanel {

    private int id;
    private FormulaPanelType type = FormulaPanelType.FORMULA;
    private String old = "";

    /**
     * Creates new form FormulaPanel.
     */
    public FormulaPanel() {
        initComponents();
        setId(0);
        jLabelErrorMessage.setText("");
        buttonGroup1.add(jRadioButtonFormula);
        buttonGroup1.add(jRadioButtonSet);
        jRadioButtonFormula.setSelected(true);
    }

    public FormulaPanel(int id) {
        initComponents();
        setId(id);
        jLabelErrorMessage.setText("");
        buttonGroup1.add(jRadioButtonFormula);
        buttonGroup1.add(jRadioButtonSet);
        addListenerToTextField();
        jRadioButtonFormula.setSelected(true);
    }

    public FormulaPanel(int id, FormulaPanelType type, String str) {
        initComponents();
        setId(id);
        jTextField1.setText(str);
        jLabelErrorMessage.setText("");
        buttonGroup1.add(jRadioButtonFormula);
        buttonGroup1.add(jRadioButtonSet);
        addListenerToTextField();
        if(type == FormulaPanelType.FORMULA)
            jRadioButtonFormula.setSelected(true);
        else
            jRadioButtonSet.setSelected(true);
    }

    /**
     * Reset the panel id.
     * @param id The new id.
     */
    public void setId(int id) {
        this.id = id;
        jLabelFormulaId.setText(String.valueOf(id+1));
    }

    public FormulaPanelType getType() {
        return type;
    }

    /**
     * Disable the formula panel's delete button.
     */
    public void enableDeleteButton(boolean b) {
        jButtonRemoveFormula.setEnabled(b);
    }

    /**
     * Returns true if this Component is the focus owner.
     * @return : true if this Component is the focus owner; false otherwise
     */
    public boolean isTextFieldFocusOwner() {
        return jTextField1.isFocusOwner();
    }

    /**
     * Insert text at the caret position in the textfield.
     * @param text
     */
    public void insertAtCaret(String text) {
        String newText = jTextField1.getText().substring(0, jTextField1.getCaretPosition())
                + text
                + jTextField1.getText().substring(jTextField1.getCaretPosition());
        jTextField1.setText(newText);
    }

    /**
     * Set the error message.
     * @param message String describing the error.
     */
    public void setErrorMessage(String message) {
        jLabelErrorMessage.setText(message);
    }

    /**
     * Return the text of the JTextField.
     * @return the text of the JTextField.
     */
    public String getText() {
        return jTextField1.getText();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jButtonRemoveFormula = new javax.swing.JButton();
        jLabelErrorMessage = new javax.swing.JLabel();
        jLabelFormulaId = new javax.swing.JLabel();
        jRadioButtonFormula = new javax.swing.JRadioButton();
        jRadioButtonSet = new javax.swing.JRadioButton();

        jButtonRemoveFormula.setText("Supprimer");
        jButtonRemoveFormula.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFormulaActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorMessage.setText("<Message d'erreur>");

        jLabelFormulaId.setText("0");

        jRadioButtonFormula.setText("Formule");
        jRadioButtonFormula.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFormulaActionPerformed(evt);
            }
        });

        jRadioButtonSet.setText("Set");
        jRadioButtonSet.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFormulaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveFormula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelErrorMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFormula)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoveFormula)
                    .addComponent(jLabelFormulaId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelErrorMessage)
                    .addComponent(jRadioButtonFormula)
                    .addComponent(jRadioButtonSet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFormulaActionPerformed
        switch(getState()) {
            case EDIT_SINGLE :
                // interdit
                break;
            case EDIT_MULTIPLE :
                if (((FormulaTablePanel)getParent()).getNumberOfFormulas() == 2) {
                    setState(State.EDIT_SINGLE);
                    ((FormulaTablePanel)getParent()).removeFormula(id);
                } else {
                    setState(State.EDIT_MULTIPLE);
                    ((FormulaTablePanel)getParent()).removeFormula(id);
                }
                break;
            case SINGLE_RESULT :
                // impossible
                break;
            case FIRST_RESULT :
                // impossible
                break;
            case INTER_RESULT :
                // impossible
                break;
            case LAST_RESULT :
                // impossible
                break;
            default :
                System.out.println("Undefined action set for the state : " + getState());
        }
    }//GEN-LAST:event_jButtonRemoveFormulaActionPerformed

    private void jRadioButtonSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSetActionPerformed
        type = FormulaPanelType.SET;
    }//GEN-LAST:event_jRadioButtonSetActionPerformed

    private void jRadioButtonFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFormulaActionPerformed
        type = FormulaPanelType.FORMULA;
    }//GEN-LAST:event_jRadioButtonFormulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonRemoveFormula;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelFormulaId;
    private javax.swing.JRadioButton jRadioButtonFormula;
    private javax.swing.JRadioButton jRadioButtonSet;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void addListenerToTextField() {
        jTextField1.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                textFieldTextUpdate();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                textFieldTextUpdate();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                textFieldTextUpdate();
            }
        });
    }

    public void textFieldTextUpdate() {
        ((FormulaTablePanel)getParent()).formulaPanelContentUpdate();
    }
}
