/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editorView;

import gui.AbstractComponentPanel;
import gui.MainFrame;
import gui.State;

/**
 *
 * @author Skander
 */
public class FormulaPanel extends AbstractComponentPanel {
    
    private int id;

    /**
     * Creates new form FormulaPanel.
     */
    public FormulaPanel() {
        id = 0;
        initComponents();
    }
    
    public FormulaPanel(int id) {
        initComponents();
        setId(id);
    }
    
    /**
     * Reset the panel id.
     * @param id The new id.
     */
    public void setId(int id) {
        this.id = id;
        jLabelFormulaId.setText(String.valueOf(id+1));
    }
    
    /**
     * Disable the formula panel's delete button.
     */
    public void enableDeleteButton(boolean b) {
        jButtonRemoveFormula.setEnabled(b);
    }

    /**
     * Returns true if this Component is the focus owner.
     * @return : true if this Component is the focus owner; false otherwise
     */
    public boolean isTextFieldFocusOwner() {
        return jTextField1.isFocusOwner();
    }
    
    /**
     * Insert text at the caret position in the textfield.
     * @param text 
     */
    public void insertAtCaret(String text) {
        String newText = jTextField1.getText().substring(0, jTextField1.getCaretPosition())
                + text
                + jTextField1.getText().substring(jTextField1.getCaretPosition());
        jTextField1.setText(newText);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButtonRemoveFormula = new javax.swing.JButton();
        jLabelErrorMessage = new javax.swing.JLabel();
        jLabelFormulaId = new javax.swing.JLabel();

        jButtonRemoveFormula.setText("Supprimer");
        jButtonRemoveFormula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveFormulaActionPerformed(evt);
            }
        });

        jLabelErrorMessage.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelErrorMessage.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorMessage.setText("<Message d'erreur>");

        jLabelFormulaId.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFormulaId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveFormula))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelErrorMessage)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRemoveFormula)
                    .addComponent(jLabelFormulaId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoveFormulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveFormulaActionPerformed
        switch(getState()) {
            case EDIT_SINGLE : 
                // interdit
                break;
            case EDIT_MULTIPLE :
                if (((FormulaTablePanel)getParent()).getNumberOfFormulas() == 2) {
                    setState(State.EDIT_SINGLE);
                    ((FormulaTablePanel)getParent()).removeFormula(id);
                } else {
                    setState(State.EDIT_MULTIPLE);
                    ((FormulaTablePanel)getParent()).removeFormula(id);
                }
                break;
            case SINGLE_RESULT :
                // impossible
                break;
            case FIRST_RESULT : 
                // impossible
                break;
            case INTER_RESULT : 
                // impossible
                break;
            case LAST_RESULT :
                // impossible
                break;
            default : 
                System.out.println("Undefined action set for the state : " + getState());
        }
    }//GEN-LAST:event_jButtonRemoveFormulaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRemoveFormula;
    private javax.swing.JLabel jLabelErrorMessage;
    private javax.swing.JLabel jLabelFormulaId;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
