/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.editorView;

/**
 *
 * @author Skander
 */
public class PalettePanel extends javax.swing.JPanel {
        
    /**
     * Creates new form ToolboxPanel
     */
    public PalettePanel(FormulaTablePanel panels) {
        initComponents();
        /*
        jToolBar1.add(new PaletteSeperationLabel("Propositions :"));
        jToolBar1.add(new InsertionButton(panels, "p", "insérer la proposition p"));
        jToolBar1.add(new InsertionButton(panels, "q", "insérer la proposition q"));
        jToolBar1.add(new InsertionButton(panels, "(p i)", "insérer la proposition (p i)"));
        jToolBar1.add(new InsertionButton(panels, "(p (i + 1))", "insérer la proposition (p (i + 1))"));
        jToolBar1.add(new InsertionButton(panels, "(p i j)", "insérer la proposition (p i j)"));
        */
        jToolBar1.add(new PaletteSeperationLabel("Bool :"));
        //TODO ajouter les insertButtons
        jToolBar1.add(new InsertionButton(panels, "True", ""));
        jToolBar1.add(new InsertionButton(panels, "False", ""));
        jToolBar1.add(new InsertionButton(panels, "(i in E)", ""));
        jToolBar1.add(new InsertionButton(panels, "(E subset F)", ""));
        jToolBar1.add(new InsertionButton(panels, "(x = y)", "test d'égalité"));
        jToolBar1.add(new InsertionButton(panels, "(<var> < <var>)", ""));
        jToolBar1.add(new InsertionButton(panels, "(<var> <= <var>)", ""));
        jToolBar1.add(new InsertionButton(panels, "(empty <set>)", ""));
        jToolBar1.add(new InsertionButton(panels, "(<bool-expr> and <bool-expr>)", ""));
        jToolBar1.add(new InsertionButton(panels, "(<bool-expr> or <bool-expr>)", ""));
        jToolBar1.add(new InsertionButton(panels, "(not <bool-expr>)", ""));
        
        jToolBar1.add(new PaletteSeperationLabel("Set :"));
        jToolBar1.add(new InsertionButton(panels, "<id> ( <var-list> )", ""));
        jToolBar1.add(new InsertionButton(panels, "<set> union <set>", ""));
        //TODO ajouter les insertButtons
    }

    public PalettePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Insérer :");
        jToolBar1.add(jLabel1);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
