/*
 *
 * Project TouIST, 2015. Easily formalize and solve real-world sized problems
 * using propositional logic and linear theory of reals with a nice GUI.
 *
 * https://github.com/olzd/touist
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * Contributors:
 *     Alexis Comte, Abdelwahab Heba, Olivier Lezaud,
 *     Skander Ben Slimane, Maël Valais
 *
 */

package gui.editorView;

/**
 *
 * @author Skander
 */
public class PalettePanel extends javax.swing.JPanel {

    /**
     * Creates new form ToolboxPanel
     */
    public PalettePanel(FormulaTablePanel panels) {
        initComponents();
        jToolBar1.add(new PaletteSeperationLabel("Propositions :"));
        jToolBar1.add(new InsertionButton(panels, "p", "insérer la proposition p"));
        jToolBar1.add(new InsertionButton(panels, "q", "insérer la proposition q"));
        jToolBar1.add(new InsertionButton(panels, "(p i)", "insérer la proposition (p i)"));
        jToolBar1.add(new InsertionButton(panels, "(p (i + 1))", "insérer la proposition (p (i + 1))"));
        jToolBar1.add(new InsertionButton(panels, "(p i j)", "insérer la proposition (p i j)"));

        jToolBar1.add(new PaletteSeperationLabel("Connecteurs :"));
        //TODO ajouter les insertButtons

        jToolBar1.add(new PaletteSeperationLabel("Macros :"));
        //TODO ajouter les insertButtons
    }

    public PalettePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Insérer :");
        jToolBar1.add(jLabel1);

        add(jToolBar1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
