
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gui.TranslatorLatex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATMOST = 59;
  public static final int DIVIDE = 43;
  public static final int WHEN = 55;
  public static final int BIGOR = 12;
  public static final int SQRT = 20;
  public static final int GREATER_OR_EQUAL = 33;
  public static final int EMPTY = 17;
  public static final int ERROR_TERM = 68;
  public static final int COMMENT = 50;
  public static final int XOR = 49;
  public static final int INTEGER = 63;
  public static final int GREATER = 32;
  public static final int INT = 9;
  public static final int TERMTUPLE = 66;
  public static final int LESSER_OR_EQUAL = 31;
  public static final int DODOT = 46;
  public static final int WHITESPACE = 22;
  public static final int DATA = 3;
  public static final int NOT = 14;
  public static final int AND = 16;
  public static final int VARTUPLE = 62;
  public static final int RCRO = 45;
  public static final int RPAR = 39;
  public static final int IN = 13;
  public static final int OR = 15;
  public static final int COMMA = 47;
  public static final int AFFECT = 27;
  public static final int SUBSTRACT = 42;
  public static final int DIFFERENT = 29;
  public static final int MULTIPLY = 41;
  public static final int LESSER = 30;
  public static final int TWODOT = 48;
  public static final int IF = 4;
  public static final int DOT = 51;
  public static final int EOF = 0;
  public static final int CARD = 19;
  public static final int EQUAL = 28;
  public static final int BIGAND = 11;
  public static final int IMPLIQUE = 36;
  public static final int TRUE = 23;
  public static final int error = 1;
  public static final int ATLEAST = 57;
  public static final int NEWLINE = 56;
  public static final int ADD = 40;
  public static final int DOUBLENUMBER = 64;
  public static final int MOD = 21;
  public static final int CONSTANT = 7;
  public static final int BOOL_AND = 34;
  public static final int TOP = 25;
  public static final int SUBSET = 18;
  public static final int BOT = 26;
  public static final int UNION = 52;
  public static final int LATEX = 69;
  public static final int ELSE = 6;
  public static final int LET = 60;
  public static final int EQUIV = 37;
  public static final int FLOAT = 10;
  public static final int THEN = 5;
  public static final int END = 2;
  public static final int LCRO = 44;
  public static final int LPAR = 38;
  public static final int BOOL_OR = 35;
  public static final int DIFF = 54;
  public static final int FALSE = 24;
  public static final int TERM = 65;
  public static final int INTER = 53;
  public static final int ALPHA = 67;
  public static final int VAR = 61;
  public static final int EXACT = 58;
  public static final int SET = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "END",
  "DATA",
  "IF",
  "THEN",
  "ELSE",
  "CONSTANT",
  "SET",
  "INT",
  "FLOAT",
  "BIGAND",
  "BIGOR",
  "IN",
  "NOT",
  "OR",
  "AND",
  "EMPTY",
  "SUBSET",
  "CARD",
  "SQRT",
  "MOD",
  "WHITESPACE",
  "TRUE",
  "FALSE",
  "TOP",
  "BOT",
  "AFFECT",
  "EQUAL",
  "DIFFERENT",
  "LESSER",
  "LESSER_OR_EQUAL",
  "GREATER",
  "GREATER_OR_EQUAL",
  "BOOL_AND",
  "BOOL_OR",
  "IMPLIQUE",
  "EQUIV",
  "LPAR",
  "RPAR",
  "ADD",
  "MULTIPLY",
  "SUBSTRACT",
  "DIVIDE",
  "LCRO",
  "RCRO",
  "DODOT",
  "COMMA",
  "TWODOT",
  "XOR",
  "COMMENT",
  "DOT",
  "UNION",
  "INTER",
  "DIFF",
  "WHEN",
  "NEWLINE",
  "ATLEAST",
  "EXACT",
  "ATMOST",
  "LET",
  "VAR",
  "VARTUPLE",
  "INTEGER",
  "DOUBLENUMBER",
  "TERM",
  "TERMTUPLE",
  "ALPHA",
  "ERROR_TERM",
  "LATEX"
  };
}

