/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.editionView.ParentEditionPanel;
import gui.resultsView.ResultsPanel;

import java.awt.CardLayout;
import java.io.File;
import java.util.Locale;

import javax.swing.JPanel;

import solution.BaseDeClauses;
import solution.ModelList;
import solution.Solver;
import translation.Translator;

/**
 *
 * @author Skander
 */
public class MainFrame extends javax.swing.JFrame {

    private BaseDeClauses clause = new BaseDeClauses();
    private Translator translator = new Translator("compiler"+File.separatorChar+"touistc.native");
    private Solver solver;
    private ModelList models;

    public State state;

    public final static String EDITOR_PANEL = "editor_panel";
    public final static String RESULTS_PANEL = "results_panel";
    private JPanel cards = new JPanel(new CardLayout());
    private ParentEditionPanel editorPanel1 = new ParentEditionPanel();
    private ResultsPanel resultsPanel1 = new ResultsPanel();
    private LanguagesController languagesController = new LanguagesController(Locale.ENGLISH);

    public LanguagesController getLang() {
        return languagesController;
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        state = State.EDITION;

        add(cards);
        cards.add(editorPanel1, EDITOR_PANEL);
        cards.add(resultsPanel1, RESULTS_PANEL);
        setViewToEditor();

        initComponents();
        
        updateLanguage();
    }
    
    private void updateLanguage() {
        this.setTitle(languagesController.getWord(LanguagesController.FRAME_TITLE));
        this.jMenu1.setText(languagesController.getWord(LanguagesController.FRAME_MENU_FILE));
        this.jMenu2.setText(languagesController.getWord(LanguagesController.FRAME_MENU_HELP));
        this.jMenu3.setText(languagesController.getWord(LanguagesController.FRAME_MENU_LANGUAGE));
        editorPanel1.updateLanguage();
        resultsPanel1.updateLanguage();
    }

    public BaseDeClauses getClause() {
        return clause;
    }

    public Solver getSolver() {
        return solver;
    }

    public void setSolver(Solver solver) {
        this.solver = solver;
    }

    public ModelList getModelList() {
        return models;
    }

    public void setModels(ModelList models) {
        this.models = models;
    }

    public Translator getTranslator() {
        return translator;
    }
    
    public void updateResultsPanelIterator() {
        resultsPanel1.updateIterator();
    }

    public void setViewToEditor() {
        ((CardLayout)cards.getLayout()).show(cards, EDITOR_PANEL);
    }

    public void setViewToResults() {
        resultsPanel1.applyRestrictions();
        ((CardLayout)cards.getLayout()).show(cards, RESULTS_PANEL);
    }
    
    public void setResultViewText(String text) {
        resultsPanel1.setText(text);
    }
    
    public void setLanguage(Locale language) {
        languagesController.setLanguage(language);
        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Language");

        jMenuItem1.setText("English");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Français");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        languagesController.setLanguage(Locale.ENGLISH);
        updateLanguage();
        System.out.println("Language set to English");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        languagesController.setLanguage(Locale.FRENCH);
        updateLanguage();
        System.out.println("Language set to French");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
			public void run() {
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
