/* The following code was generated by JFlex 1.6.1 */

package gui.TranslatorLatex;

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Latex.flex</tt>
 */
class Lexi implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\5\1\61\1\3\1\3\22\0\1\3\1\42\2\0"+
    "\1\7\1\0\1\45\1\0\1\47\1\50\1\52\1\51\1\57\1\53"+
    "\1\6\1\54\12\1\1\60\1\10\1\43\1\41\1\44\1\7\1\0"+
    "\1\2\1\40\21\2\1\37\6\2\1\55\1\0\1\56\1\0\1\4"+
    "\1\0\1\12\1\26\1\24\1\11\1\14\1\17\1\27\1\20\1\16"+
    "\2\2\1\21\1\32\1\15\1\25\1\33\1\36\1\30\1\22\1\13"+
    "\1\35\1\2\1\23\1\31\1\34\1\2\1\0\1\46\10\0\1\61"+
    "\u1fa2\0\1\61\1\61\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\1"+
    "\22\3\1\6\1\1\1\7\1\10\2\1\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\2\0\1\23\1\0\1\24\1\4\13\3\1\25\1\26"+
    "\11\3\1\27\6\3\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\4\3\1\40\2\3\1\41\3\3"+
    "\1\42\1\43\2\3\1\44\1\45\6\3\1\46\1\47"+
    "\1\3\1\50\1\51\1\52\1\53\1\54\2\3\1\55"+
    "\1\56\1\57\6\3\1\60\1\61\1\62\6\3\1\63"+
    "\1\64\1\65\1\66\1\67\3\3\1\70\1\71\1\3"+
    "\1\72\1\73\1\3\1\74\1\75\1\3\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e"+
    "\0\u04b0\0\u04e2\0\u0514\0\u0546\0\u0578\0\u05aa\0\u05dc\0\u060e"+
    "\0\u0640\0\62\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\62\0\372\0\u0672\0\62\0\u015e\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\u08ca\0\u08fc\0\u092e\0\226\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\226"+
    "\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\62\0\62"+
    "\0\62\0\u0c4e\0\62\0\62\0\62\0\u0672\0\u0c80\0\u0cb2"+
    "\0\u0ce4\0\u0d16\0\226\0\u0d48\0\u0d7a\0\226\0\u0dac\0\u0dde"+
    "\0\u0e10\0\226\0\u0e42\0\u0e74\0\u0ea6\0\226\0\226\0\u0ed8"+
    "\0\u0f0a\0\u0f3c\0\u0f6e\0\u0fa0\0\u0fd2\0\226\0\226\0\u1004"+
    "\0\226\0\226\0\62\0\226\0\226\0\u1036\0\u1068\0\226"+
    "\0\226\0\226\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162\0\u1194"+
    "\0\226\0\226\0\226\0\u11c6\0\u11f8\0\u122a\0\u125c\0\u128e"+
    "\0\u12c0\0\226\0\226\0\226\0\226\0\226\0\u12f2\0\u1324"+
    "\0\u1356\0\226\0\226\0\u1388\0\226\0\226\0\u13ba\0\226"+
    "\0\226\0\u13ec\0\226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\4\1\21\1\22\1\23\1\24\1\25\1\26\2\4"+
    "\1\27\1\30\2\4\1\31\1\4\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\64\0"+
    "\1\3\1\4\1\0\1\54\1\0\1\55\2\0\30\4"+
    "\22\0\2\4\1\0\1\4\4\0\30\4\24\0\1\5"+
    "\1\0\1\5\55\0\1\54\1\4\1\0\1\54\4\0"+
    "\30\4\27\0\1\56\54\0\1\57\1\60\1\0\1\57"+
    "\4\0\30\60\31\0\1\61\52\0\2\4\1\0\1\4"+
    "\4\0\1\4\1\62\3\4\1\63\22\4\22\0\2\4"+
    "\1\0\1\4\4\0\2\4\1\64\1\4\1\65\23\4"+
    "\22\0\2\4\1\0\1\4\4\0\7\4\1\66\7\4"+
    "\1\67\10\4\22\0\2\4\1\0\1\4\4\0\4\4"+
    "\1\70\3\4\1\71\7\4\1\72\1\73\6\4\22\0"+
    "\2\4\1\0\1\4\4\0\14\4\1\74\13\4\22\0"+
    "\2\4\1\0\1\4\4\0\4\4\1\75\1\4\1\76"+
    "\21\4\22\0\2\4\1\0\1\4\4\0\1\4\1\77"+
    "\6\4\1\100\17\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\101\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\102\20\4\1\103\1\104\2\4\22\0\2\4"+
    "\1\0\1\4\4\0\7\4\1\105\20\4\22\0\2\4"+
    "\1\0\1\4\4\0\1\4\1\106\12\4\1\107\13\4"+
    "\22\0\2\4\1\0\1\4\4\0\17\4\1\110\10\4"+
    "\22\0\2\4\1\0\1\4\4\0\5\4\1\111\22\4"+
    "\22\0\2\4\1\0\1\4\4\0\14\4\1\112\13\4"+
    "\22\0\2\4\1\0\1\4\4\0\14\4\1\113\13\4"+
    "\22\0\2\4\1\0\1\4\4\0\4\4\1\114\23\4"+
    "\22\0\2\4\1\0\1\4\4\0\14\4\1\115\13\4"+
    "\22\0\2\4\1\0\1\4\4\0\14\4\1\116\13\4"+
    "\62\0\1\117\2\0\1\120\56\0\1\121\61\0\1\122"+
    "\61\0\1\123\65\0\1\124\62\0\1\125\14\0\1\126"+
    "\61\0\2\60\1\0\1\60\4\0\30\60\21\0\5\61"+
    "\1\0\54\61\1\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\127\25\4\22\0\2\4\1\0\1\4\4\0\6\4"+
    "\1\130\21\4\22\0\2\4\1\0\1\4\4\0\10\4"+
    "\1\131\10\4\1\132\6\4\22\0\2\4\1\0\1\4"+
    "\4\0\1\133\27\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\134\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\24\4\1\135\3\4\22\0\2\4\1\0\1\4\4\0"+
    "\1\136\27\4\22\0\2\4\1\0\1\4\4\0\11\4"+
    "\1\137\16\4\22\0\2\4\1\0\1\4\4\0\1\4"+
    "\1\140\26\4\22\0\2\4\1\0\1\4\4\0\22\4"+
    "\1\141\5\4\22\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\142\25\4\22\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\143\25\4\22\0\2\4\1\0\1\4\4\0\10\4"+
    "\1\144\17\4\22\0\2\4\1\0\1\4\4\0\14\4"+
    "\1\145\13\4\22\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\146\25\4\22\0\2\4\1\0\1\4\4\0\2\4"+
    "\1\147\25\4\22\0\2\4\1\0\1\4\4\0\15\4"+
    "\1\150\12\4\22\0\2\4\1\0\1\4\4\0\17\4"+
    "\1\151\10\4\22\0\2\4\1\0\1\4\4\0\3\4"+
    "\1\152\24\4\22\0\2\4\1\0\1\4\4\0\17\4"+
    "\1\153\10\4\22\0\2\4\1\0\1\4\4\0\4\4"+
    "\1\154\23\4\22\0\2\4\1\0\1\4\4\0\16\4"+
    "\1\155\11\4\22\0\2\4\1\0\1\4\4\0\17\4"+
    "\1\156\10\4\22\0\2\4\1\0\1\4\4\0\1\157"+
    "\27\4\22\0\2\4\1\0\1\4\4\0\5\4\1\160"+
    "\22\4\22\0\2\4\1\0\1\4\4\0\22\4\1\161"+
    "\5\4\22\0\2\4\1\0\1\4\4\0\2\4\1\162"+
    "\25\4\65\0\1\163\16\0\2\4\1\0\1\4\4\0"+
    "\1\4\1\164\26\4\22\0\2\4\1\0\1\4\4\0"+
    "\6\4\1\165\21\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\166\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\14\4\1\167\13\4\22\0\2\4\1\0\1\4\4\0"+
    "\4\4\1\170\23\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\171\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\172\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\13\4\1\173\14\4\22\0\2\4\1\0\1\4\4\0"+
    "\2\4\1\174\25\4\22\0\2\4\1\0\1\4\4\0"+
    "\3\4\1\175\24\4\22\0\2\4\1\0\1\4\4\0"+
    "\11\4\1\176\16\4\22\0\2\4\1\0\1\4\4\0"+
    "\1\4\1\177\26\4\22\0\2\4\1\0\1\4\4\0"+
    "\11\4\1\200\16\4\22\0\2\4\1\0\1\4\4\0"+
    "\2\4\1\201\25\4\22\0\2\4\1\0\1\4\4\0"+
    "\4\4\1\202\23\4\22\0\2\4\1\0\1\4\4\0"+
    "\1\203\27\4\22\0\2\4\1\0\1\4\4\0\11\4"+
    "\1\204\16\4\22\0\2\4\1\0\1\4\4\0\1\4"+
    "\1\205\12\4\1\206\13\4\22\0\2\4\1\0\1\4"+
    "\4\0\14\4\1\207\13\4\22\0\2\4\1\0\1\4"+
    "\4\0\1\4\1\210\26\4\22\0\2\4\1\0\1\4"+
    "\4\0\11\4\1\211\16\4\22\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\212\25\4\22\0\2\4\1\0\1\4"+
    "\4\0\23\4\1\213\4\4\22\0\2\4\1\0\1\4"+
    "\4\0\17\4\1\214\10\4\22\0\2\4\1\0\1\4"+
    "\4\0\3\4\1\215\24\4\22\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\216\25\4\22\0\2\4\1\0\1\4"+
    "\4\0\3\4\1\217\24\4\22\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\220\25\4\22\0\2\4\1\0\1\4"+
    "\4\0\4\4\1\221\23\4\22\0\2\4\1\0\1\4"+
    "\4\0\17\4\1\222\10\4\22\0\2\4\1\0\1\4"+
    "\4\0\4\4\1\223\23\4\22\0\2\4\1\0\1\4"+
    "\4\0\11\4\1\224\16\4\22\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\225\25\4\22\0\2\4\1\0\1\4"+
    "\4\0\2\4\1\226\25\4\22\0\2\4\1\0\1\4"+
    "\4\0\1\4\1\227\26\4\22\0\2\4\1\0\1\4"+
    "\4\0\1\230\27\4\22\0\2\4\1\0\1\4\4\0"+
    "\2\4\1\231\25\4\22\0\2\4\1\0\1\4\4\0"+
    "\4\4\1\232\23\4\22\0\2\4\1\0\1\4\4\0"+
    "\2\4\1\233\25\4\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5150];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\37\1\12\11\2\0\1\11\1\0\37\1"+
    "\3\11\1\1\3\11\35\1\1\11\50\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[155];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexi(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 180) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(sym.ERROR_IDENTIFIER,new String(yytext()));
            }
          case 63: break;
          case 2: 
            { return symbol(sym.INTEGER,new String(yytext()));
            }
          case 64: break;
          case 3: 
            { return symbol(sym.IDENTIFIER,new String(yytext().replace("_", "\\_")));
            }
          case 65: break;
          case 4: 
            { 
            }
          case 66: break;
          case 5: 
            { return symbol(sym.DOT);
            }
          case 67: break;
          case 6: 
            { return symbol(sym.AFFECT);
            }
          case 68: break;
          case 7: 
            { return symbol(sym.LESSER);
            }
          case 69: break;
          case 8: 
            { return symbol(sym.GREATER);
            }
          case 70: break;
          case 9: 
            { return symbol(sym.LPAR);
            }
          case 71: break;
          case 10: 
            { return symbol(sym.RPAR);
            }
          case 72: break;
          case 11: 
            { return symbol(sym.ADD);
            }
          case 73: break;
          case 12: 
            { return symbol(sym.MULTIPLY);
            }
          case 74: break;
          case 13: 
            { return symbol(sym.SUBSTRACT);
            }
          case 75: break;
          case 14: 
            { return symbol(sym.DIVIDE);
            }
          case 76: break;
          case 15: 
            { return symbol(sym.LCRO);
            }
          case 77: break;
          case 16: 
            { return symbol(sym.RCRO);
            }
          case 78: break;
          case 17: 
            { return symbol(sym.COMMA);
            }
          case 79: break;
          case 18: 
            { return symbol(sym.TWODOT);
            }
          case 80: break;
          case 19: 
            { return symbol(sym.DODOT);
            }
          case 81: break;
          case 20: 
            { return symbol(sym.VAR,new String(yytext().substring(1).replace("_", "\\_")));
            }
          case 82: break;
          case 21: 
            { return symbol(sym.IN);
            }
          case 83: break;
          case 22: 
            { return symbol(sym.IF);
            }
          case 84: break;
          case 23: 
            { return symbol(sym.OR);
            }
          case 85: break;
          case 24: 
            { return symbol(sym.EQUAL);
            }
          case 86: break;
          case 25: 
            { return symbol(sym.IMPLIQUE);
            }
          case 87: break;
          case 26: 
            { return symbol(sym.DIFFERENT);
            }
          case 88: break;
          case 27: 
            { return symbol(sym.LESSER_OR_EQUAL);
            }
          case 89: break;
          case 28: 
            { return symbol(sym.GREATER_OR_EQUAL);
            }
          case 90: break;
          case 29: 
            { return symbol(sym.BOOL_AND);
            }
          case 91: break;
          case 30: 
            { return symbol(sym.BOOL_OR);
            }
          case 92: break;
          case 31: 
            { return symbol(sym.DOUBLENUMBER,new String(yytext()));
            }
          case 93: break;
          case 32: 
            { return symbol(sym.AND);
            }
          case 94: break;
          case 33: 
            { return symbol(sym.END);
            }
          case 95: break;
          case 34: 
            { return symbol(sym.NOT);
            }
          case 96: break;
          case 35: 
            { return symbol(sym.INT);
            }
          case 97: break;
          case 36: 
            { return symbol(sym.LET);
            }
          case 98: break;
          case 37: 
            { return symbol(sym.SET);
            }
          case 99: break;
          case 38: 
            { return symbol(sym.XOR);
            }
          case 100: break;
          case 39: 
            { return symbol(sym.MOD);
            }
          case 101: break;
          case 40: 
            { return symbol(sym.TOP);
            }
          case 102: break;
          case 41: 
            { return symbol(sym.BOT);
            }
          case 103: break;
          case 42: 
            { return symbol(sym.EQUIV);
            }
          case 104: break;
          case 43: 
            { return symbol(sym.DATA);
            }
          case 105: break;
          case 44: 
            { return symbol(sym.DIFF);
            }
          case 106: break;
          case 45: 
            { return symbol(sym.THEN);
            }
          case 107: break;
          case 46: 
            { return symbol(sym.TRUE);
            }
          case 108: break;
          case 47: 
            { return symbol(sym.ELSE);
            }
          case 109: break;
          case 48: 
            { return symbol(sym.SQRT);
            }
          case 110: break;
          case 49: 
            { return symbol(sym.WHEN);
            }
          case 111: break;
          case 50: 
            { return symbol(sym.CARD);
            }
          case 112: break;
          case 51: 
            { return symbol(sym.EXACT);
            }
          case 113: break;
          case 52: 
            { return symbol(sym.EMPTY);
            }
          case 114: break;
          case 53: 
            { return symbol(sym.INTER);
            }
          case 115: break;
          case 54: 
            { return symbol(sym.FALSE);
            }
          case 116: break;
          case 55: 
            { return symbol(sym.FLOAT);
            }
          case 117: break;
          case 56: 
            { return symbol(sym.BIGOR);
            }
          case 118: break;
          case 57: 
            { return symbol(sym.UNION);
            }
          case 119: break;
          case 58: 
            { return symbol(sym.ATMOST);
            }
          case 120: break;
          case 59: 
            { return symbol(sym.SUBSET);
            }
          case 121: break;
          case 60: 
            { return symbol(sym.BIGAND);
            }
          case 122: break;
          case 61: 
            { return symbol(sym.ATLEAST);
            }
          case 123: break;
          case 62: 
            { return symbol(sym.CONSTANT);
            }
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
