/*
 *
 * Project TouIST, 2015. Easily formalize and solve real-world sized problems
 * using propositional logic and linear theory of reals with a nice GUI.
 *
 * https://github.com/touist/touist
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * Contributors:
 *     Alexis Comte, Abdelwahab Heba, Olivier Lezaud,
 *     Skander Ben Slimane, Maël Valais
 *
 */

package gui.editionView;

import java.awt.GridLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Skander
 */
public class PaletteSectionPanel extends javax.swing.JPanel {

    private List<InsertionButton> buttons;
    private ImageIcon foldedIcon;
    private ImageIcon unfoldedIcon;
    private boolean isFold;

    
    /**
     * Creates new form NewPaletteSectionPanel
     * @param name section name.
     */
    public PaletteSectionPanel(String name) {
        initComponents();
        jLabelName.setText(name);
        jButtonFold.setText("");
        try {
			foldedIcon = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/paletteSectionFolded.png")));
	        unfoldedIcon = new ImageIcon(ImageIO.read(getClass().getResourceAsStream("/images/paletteSectionUnfolded.png")));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        jButtonFold.setIcon(foldedIcon);
        buttons = new ArrayList<InsertionButton>();
        isFold = true;
    }
    
    public void setText(String name) {
    	jLabelName.setText(name);
    }
    
    public List<InsertionButton> getButtons() {
        return buttons;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jButtonFold = new javax.swing.JButton();
        jPanelsContent = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("<section>");

        jButtonFold.setText(">");
        jButtonFold.setBorderPainted(false);
        jButtonFold.setContentAreaFilled(false);
        jButtonFold.setFocusable(false);
        jButtonFold.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonFold.setPreferredSize(new java.awt.Dimension(22, 22));
        jButtonFold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoldActionPerformed(evt);
            }
        });

        jPanelsContent.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelsContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 10, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButtonFold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addComponent(jPanelsContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoldActionPerformed
        isFold = !isFold;
        if (isFold) {
            jButtonFold.setIcon(foldedIcon);
            jPanelsContent.removeAll();
            jPanelsContent.updateUI();
        } else {
            jButtonFold.setIcon(unfoldedIcon);
            jPanelsContent.setLayout(new GridLayout(buttons.size(), 1));
            for (InsertionButton button : buttons) {
                jPanelsContent.add(button);
            }
            jPanelsContent.updateUI();
        }
    }//GEN-LAST:event_jButtonFoldActionPerformed

public void addInsertButton(InsertionButton button) {
    buttons.add(button);
    updateUI();
}

public void fold() {
    isFold = true;
    jButtonFold.setIcon(foldedIcon);
    jPanelsContent.removeAll();
    jPanelsContent.updateUI();
}

public void unfold() {
    isFold = false;
    jButtonFold.setIcon(unfoldedIcon);
    jPanelsContent.setLayout(new GridLayout(buttons.size(), 1));
    for (InsertionButton button : buttons) {
        jPanelsContent.add(button);
    }
    updateUI();
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFold;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPanelsContent;
    // End of variables declaration//GEN-END:variables
}
