/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.resultsView;

import gui.AbstractComponentPanel;
import gui.State;

/**
 *
 * @author Skander
 */
public class ResultsPanel extends AbstractComponentPanel {

    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel() {
        initComponents();
    }

    /**
     * Enable the next and previous buttons depending on the frame state.
     */
    public void applyRestrictions() {
        switch(getState()) {
            case EDIT_SINGLE : 
                // impossible
                break;
            case EDIT_MULTIPLE :
                // impossible
                break;
            case SINGLE_RESULT :
                jButtonNext.setEnabled(false);
                jButtonPrevious.setEnabled(false);
                break;
            case FIRST_RESULT : 
                jButtonNext.setEnabled(true);
                jButtonPrevious.setEnabled(false);
                break;
            case INTER_RESULT : 
                jButtonNext.setEnabled(true);
                jButtonPrevious.setEnabled(true);
                break;
            case LAST_RESULT :
                jButtonNext.setEnabled(false);
                jButtonPrevious.setEnabled(true);
                break;
            default : 
                System.out.println("Undefined action set for the state : " + getState());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonEditor = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Résultats");

        jButtonEditor.setText("Retour en édition");
        jButtonEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditorActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Précédent");

        jButtonNext.setText("Suivant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)
                        .addGap(0, 374, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonEditor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrevious)
                    .addComponent(jButtonNext))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditorActionPerformed
        switch(getState()) {
            case EDIT_SINGLE :
                // impossible
                break;
            case EDIT_MULTIPLE :
                // impossible
                break;
            case SINGLE_RESULT :
                if(getFrame().getNumberOfFormulas() > 1) {
                    setState(State.EDIT_MULTIPLE);
                    getFrame().setViewToEditor();
                } else {
                    setState(State.EDIT_SINGLE);
                    getFrame().setViewToEditor();
                }
                break;
            case FIRST_RESULT :
                if(getFrame().getNumberOfFormulas() > 1) {
                    setState(State.EDIT_MULTIPLE);
                    getFrame().setViewToEditor();
                } else {
                    setState(State.EDIT_SINGLE);
                    getFrame().setViewToEditor();
                }
                break;
            case INTER_RESULT : 
                if(getFrame().getNumberOfFormulas() > 1) {
                    setState(State.EDIT_MULTIPLE);
                    getFrame().setViewToEditor();
                } else {
                    setState(State.EDIT_SINGLE);
                    getFrame().setViewToEditor();
                }
                break;
            case LAST_RESULT :
                if(getFrame().getNumberOfFormulas() > 1) {
                    setState(State.EDIT_MULTIPLE);
                    getFrame().setViewToEditor();
                } else {
                    setState(State.EDIT_SINGLE);
                    getFrame().setViewToEditor();
                }
                break;
            default : 
                System.out.println("Undefined action set for the state : " + getState());
        }
        getFrame().setViewToEditor();
    }//GEN-LAST:event_jButtonEditorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditor;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
