/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.menu;

import gui.AbstractComponentPanel;
import gui.Lang;
import gui.MainFrame;
import gui.SolverSelection;
import java.io.File;
import java.util.Locale;
import javax.swing.JDialog;
import javax.swing.JFileChooser;

/**
 *
 * @author Skander
 */
public class SettingsPanel extends AbstractComponentPanel {

    /*
    Adding items in jComboBoxLanguages launches an ActionEvent,
    to prevent that, we will set jComboBoxLanguagesEnable to true
    once all items are added.
     */
    private boolean jComboBoxLanguagesEnabled = false;
    
    public SettingsPanel(MainFrame parent) {
        initComponents();
        
        this.parent = parent;
        updateLanguage();
        
        buttonGroup1.add(SAT4J);
        buttonGroup1.add(YCES);
        buttonGroup2.add(SMTLQFLRA);
        buttonGroup2.add(SMTLQFLIA);
        buttonGroup2.add(SMTLQFRDL);
        buttonGroup2.add(SMTLQFIDL);
        
        switch(parent.getSolverSelection().getSelectedSolver()) {
            case SAT : 
                SAT4J.setSelected(true);
                break;
            case QF_LRA : 
                YCES.setSelected(true);
                SMTLQFLRA.setSelected(true);
                break;
            case QF_LIA : 
                YCES.setSelected(true);
                SMTLQFLIA.setSelected(true);
                break;
            case QF_RDL : 
                YCES.setSelected(true);
                SMTLQFRDL.setSelected(true);
                break;
            case QF_IDL : 
                YCES.setSelected(true);
                SMTLQFIDL.setSelected(true);
                break;
            default :
        }
        updateRadioButtons();
        
        choiceLanguage.removeAllItems();
        for (Locale locale : parent.getLang().getSupportedLanguages()) {
            choiceLanguage.addItem(locale);
        }
        jComboBoxLanguagesEnabled = true; 
        choiceLanguage.setSelectedItem(parent.getLang().getLanguage());
    }
    
    private MainFrame parent = null;
    
    /**
     * Creates new form Settings
     */
    public SettingsPanel() {
        initComponents();
        
        buttonGroup1.add(SAT4J);
        buttonGroup1.add(YCES);
        buttonGroup2.add(SMTLQFLRA);
        buttonGroup2.add(SMTLQFLIA);
        buttonGroup2.add(SMTLQFRDL);
        buttonGroup2.add(SMTLQFIDL);
        updateRadioButtons();
        
        choiceLanguage.removeAllItems();
        for (Locale locale : parent.getLang().getSupportedLanguages()) {
            choiceLanguage.addItem(locale);
        }
    }
    
    public void updateRadioButtons() {
        SMTLQFLRA.setEnabled(! SAT4J.isSelected());
        SMTLQFLIA.setEnabled(! SAT4J.isSelected());
        SMTLQFRDL.setEnabled(! SAT4J.isSelected());
        SMTLQFIDL.setEnabled(! SAT4J.isSelected());
        updateUI();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tabs = new javax.swing.JTabbedPane();
        generalSettings = new javax.swing.JPanel();
        labelDefaultDirectory = new javax.swing.JLabel();
        pathDefaultDirectory = new javax.swing.JTextField();
        changeDefaultDirectory = new javax.swing.JButton();
        solverSettings = new javax.swing.JPanel();
        SAT4J = new javax.swing.JRadioButton();
        YCES = new javax.swing.JRadioButton();
        SMTLQFLRA = new javax.swing.JRadioButton();
        SMTLQFLIA = new javax.swing.JRadioButton();
        SMTLQFRDL = new javax.swing.JRadioButton();
        SMTLQFIDL = new javax.swing.JRadioButton();
        chooseSolverText = new javax.swing.JLabel();
        languageSettings = new javax.swing.JPanel();
        chooseLanguageText = new javax.swing.JLabel();
        choiceLanguage = new javax.swing.JComboBox();

        labelDefaultDirectory.setText("Default directory");

        pathDefaultDirectory.setEditable(false);
        pathDefaultDirectory.setText("path");

        changeDefaultDirectory.setText("Change");
        changeDefaultDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDefaultDirectoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout generalSettingsLayout = new javax.swing.GroupLayout(generalSettings);
        generalSettings.setLayout(generalSettingsLayout);
        generalSettingsLayout.setHorizontalGroup(
            generalSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalSettingsLayout.createSequentialGroup()
                        .addComponent(labelDefaultDirectory)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(generalSettingsLayout.createSequentialGroup()
                        .addComponent(pathDefaultDirectory, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(changeDefaultDirectory)))
                .addContainerGap())
        );
        generalSettingsLayout.setVerticalGroup(
            generalSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDefaultDirectory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathDefaultDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeDefaultDirectory))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        tabs.addTab("General", generalSettings);

        SAT4J.setSelected(true);
        SAT4J.setText("SAT4J");
        SAT4J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAT4JActionPerformed(evt);
            }
        });

        YCES.setText("YCES");
        YCES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YCESActionPerformed(evt);
            }
        });

        SMTLQFLRA.setText("SMT_QF_LRA");
        SMTLQFLRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMTLQFLRAActionPerformed(evt);
            }
        });

        SMTLQFLIA.setText("SMT_QF_LIA");
        SMTLQFLIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMTLQFLIAActionPerformed(evt);
            }
        });

        SMTLQFRDL.setText("SMT_QF_RDL");
        SMTLQFRDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMTLQFRDLActionPerformed(evt);
            }
        });

        SMTLQFIDL.setText("SMT_QF_IDL");
        SMTLQFIDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMTLQFIDLActionPerformed(evt);
            }
        });

        chooseSolverText.setText("Choose your solver");

        javax.swing.GroupLayout solverSettingsLayout = new javax.swing.GroupLayout(solverSettings);
        solverSettings.setLayout(solverSettingsLayout);
        solverSettingsLayout.setHorizontalGroup(
            solverSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solverSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(solverSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solverSettingsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(solverSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SMTLQFRDL)
                            .addComponent(SMTLQFLIA)
                            .addComponent(SMTLQFLRA)
                            .addComponent(SMTLQFIDL)))
                    .addComponent(SAT4J)
                    .addComponent(YCES)
                    .addComponent(chooseSolverText))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        solverSettingsLayout.setVerticalGroup(
            solverSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solverSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseSolverText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SAT4J)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YCES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SMTLQFLRA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SMTLQFLIA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SMTLQFRDL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SMTLQFIDL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Solver", solverSettings);

        chooseLanguageText.setText("Language");

        choiceLanguage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choiceLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceLanguageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout languageSettingsLayout = new javax.swing.GroupLayout(languageSettings);
        languageSettings.setLayout(languageSettingsLayout);
        languageSettingsLayout.setHorizontalGroup(
            languageSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languageSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chooseLanguageText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(choiceLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        languageSettingsLayout.setVerticalGroup(
            languageSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(languageSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(languageSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseLanguageText)
                    .addComponent(choiceLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        tabs.addTab("Language", languageSettings);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        tabs.getAccessibleContext().setAccessibleName("General");
    }// </editor-fold>//GEN-END:initComponents

    private void changeDefaultDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDefaultDirectoryActionPerformed
        JFileChooser jFileChooser = new JFileChooser(new File(System.getProperty("user.dir")));
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = jFileChooser.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION && jFileChooser.getSelectedFile() != null) {
            String path = jFileChooser.getSelectedFile().getPath();
            pathDefaultDirectory.setText(path);
        }
        
    }//GEN-LAST:event_changeDefaultDirectoryActionPerformed

    private void choiceLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceLanguageActionPerformed
        if (jComboBoxLanguagesEnabled && choiceLanguage.getSelectedIndex() >= 0) {
            Locale selectedLanguage = (Locale)choiceLanguage.getSelectedItem();
            parent.setLanguage(selectedLanguage);
            parent.updateLanguage();
            updateLanguage();
        }
    }//GEN-LAST:event_choiceLanguageActionPerformed

    private void SAT4JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAT4JActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.SAT);
        SMTLQFLRA.setSelected(false);
        SMTLQFLIA.setSelected(false);
        SMTLQFRDL.setSelected(false);
        SMTLQFIDL.setSelected(false);
        updateRadioButtons();
    }//GEN-LAST:event_SAT4JActionPerformed

    private void YCESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YCESActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.QF_LRA);
        SMTLQFLRA.setSelected(true);
        updateRadioButtons();
    }//GEN-LAST:event_YCESActionPerformed

    private void SMTLQFLIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMTLQFLIAActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.QF_LIA);
        updateRadioButtons();
    }//GEN-LAST:event_SMTLQFLIAActionPerformed

    private void SMTLQFLRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMTLQFLRAActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.QF_LRA);
        updateRadioButtons();
    }//GEN-LAST:event_SMTLQFLRAActionPerformed

    private void SMTLQFRDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMTLQFRDLActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.QF_RDL);
        updateRadioButtons();
    }//GEN-LAST:event_SMTLQFRDLActionPerformed

    private void SMTLQFIDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMTLQFIDLActionPerformed
        parent.getSolverSelection().setSelectedSolver(SolverSelection.SolverType.QF_IDL);
        updateRadioButtons();
    }//GEN-LAST:event_SMTLQFIDLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SAT4J;
    private javax.swing.JRadioButton SMTLQFIDL;
    private javax.swing.JRadioButton SMTLQFLIA;
    private javax.swing.JRadioButton SMTLQFLRA;
    private javax.swing.JRadioButton SMTLQFRDL;
    private javax.swing.JRadioButton YCES;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton changeDefaultDirectory;
    private javax.swing.JComboBox choiceLanguage;
    private javax.swing.JLabel chooseLanguageText;
    private javax.swing.JLabel chooseSolverText;
    private javax.swing.JPanel generalSettings;
    private javax.swing.JLabel labelDefaultDirectory;
    private javax.swing.JPanel languageSettings;
    private javax.swing.JTextField pathDefaultDirectory;
    private javax.swing.JPanel solverSettings;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateLanguage() {
        if (getParent() != null && getRootPane().getParent() instanceof JDialog) {
            ((JDialog)(getRootPane().getParent())).setTitle(parent.getLang().getWord(Lang.SETTINGS_TITLE));
        }
        tabs.setTitleAt(0, parent.getLang().getWord(Lang.SETTINGS_GENERAL_TITLE));
        tabs.setTitleAt(1, parent.getLang().getWord(Lang.SETTINGS_SOLVER_TITLE));
        tabs.setTitleAt(2, parent.getLang().getWord(Lang.SETTINGS_LANGUAGE_TITLE));
        labelDefaultDirectory.setText(parent.getLang().getWord(Lang.SETTINGS_GENERAL_TEXT));
        changeDefaultDirectory.setText(parent.getLang().getWord(Lang.SETTINGS_GENERAL_BUTTON));
        chooseSolverText.setText(parent.getLang().getWord(Lang.SETTINGS_SOLVER_TEXT));
        chooseLanguageText.setText(parent.getLang().getWord(Lang.SETTINGS_LANGUAGE_TEXT));
    }
}
