package translation;

/**
 * This class holds one error that might be generated by the translator,
 * with the format (row,column,error_text)
 * @author maelv
 */
public class TranslationError {
	private int rowInCode;
	private int columnInCode;
	private String errorMessage;

	public TranslationError(int rowInCode, int columnInCode, String errorMessage) {
		this.rowInCode = rowInCode;
		this.columnInCode = columnInCode;
		this.errorMessage = errorMessage;
	}

	@Override
	public String toString() {
		return "The Touistl translator returned an error:\n"
				+"In line "+rowInCode+", column "+columnInCode+": "
				+errorMessage;
	}

	public int getRowInCode() {
		return rowInCode;
	}

	public int getColumnInCode() {
		return columnInCode;
	}

	public String getErrorMessage() {
		return errorMessage;
	}

}
